### ISSUE TITLE
Gemini PDA config recommendations

### ISSUE THREAD

**Issue by ca-d** [adisbladis/nixconfig#2]
Hej @adisbladis , does the `gari` configuration at 
 https://github.com/adisbladis/nixconfig/blob/4095fcd55961ff5fda8ead617f105d6c641c74f2/hosts/gari/configuration.nix#L86 actually work on a Gemini PDA? If so, is it close to a default Gemini PDA configuration you would recommend deploying and what were the steps involved in getting this running for you? If not, do you know of any better default Gemini PDA config file to use as a starting point for a fresh installation?

Thanks in advance for any advice you may be able to give 🙏

**Comment by r2r-dev** [comment]
afaik this part of config just changes udev rules on a host, which is required to get sp-flash-tool to run on a linux based OSes:
https://support.planetcom.co.uk/index.php/Linux_Flashing_Guide

also, here's nix flake for said flash tool:
https://github.com/r2r-dev/gemini-flashtool-flake

**Comment by ca-d** [comment]
> also, here's nix flake for said flash tool:
> https://github.com/r2r-dev/gemini-flashtool-flake

Thanks for the clarification and the flake!
