### ISSUE TITLE
Question about your node setup

### ISSUE THREAD

**Issue by jankaifer** [adisbladis/nixconfig#3]
Sorry for pinging here, but I wanted to ask you how do you handle node setup.
I've seen that you were active with pnpm a few years ago, but I haven't found any node setup in your config.

I currently use `fnm` with `corepack` and It's broken since `pnpm@7.6.0` so I'm looking at something which could fix it for me.

Essentially `pnpm` is installing dependencies outside of `steam-run` which leads to those weird `node: file not found` errors.

**Comment by jankaifer** [comment]
For anyone looking into this, I started using this and it solved all my issues with nix:

https://github.com/Mic92/nix-ld

**Comment by adisbladis** [comment]
I don't use pnpm anymore, and most of my use before was in private repos.
